from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By

opts=webdriver.ChromeOptions()
# opts.add_experimental_option('detach',True)

# opts.add_argument('--headless')
driver=webdriver.Chrome(options=opts)
driver.get('https://www.cricbuzz.com/')
sleep(1)

print('By ID')
leaderboard=driver.find_elements(By.ID,'leaderboard')
print('id found')
google_ads=driver.find_elements(By.ID,'google_ads_iframe_/1024780/Desktop_new/LB/Home_0__container__')
print('id found')
main_header=driver.find_element(By.ID,'main-header')
print('id found')
shosh=driver.find_element(By.ID,'shosh')
print('id found')
match_carousel=driver.find_element(By.ID,'match-carousel')
print('id found')
print('ID done!')

print('By NAME')
robots=driver.find_element(By.NAME,'robots')
print('name found')
viewport=driver.find_element(By.NAME,'viewport')
print('name found')
description=driver.find_element(By.NAME,'description')
print('name found')
google_bot=driver.find_element(By.NAME,'googlebot')
print('name found')
google_site_verification=driver.find_element(By.NAME,'google-site-verification')
print('name verified')
print('NAME done!')

print('By CLASS')
Bold_font=driver.find_element(By.CLASS_NAME,'font-bold')
print('class found')
XL_text=driver.find_element(By.CLASS_NAME,'text-xl')
print('class found')
Mt_6=driver.find_element(By.CLASS_NAME,'mt-6')
print('class found')
col_span=driver.find_element(By.CLASS_NAME,'col-span-9')
print('class found')
background=driver.find_element(By.CLASS_NAME,'bg-white')
print('class found')
print('CLASS done!')